# Generated by Django 4.2.1 on 2023-07-01 05:58

import CORE.WeddingPlanner.WpGig.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('WpSeller', '0001_initial'),
        ('WpService', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=250)),
                ('location', models.CharField(default='Anywhere', max_length=50)),
                ('description', models.TextField(default='')),
                ('thumbnail', models.ImageField(null=True, upload_to=CORE.WeddingPlanner.WpGig.models.upload_location)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WpSeller.portfolio')),
                ('service_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='WpService.service')),
            ],
            options={
                'db_table': 'core_wpgig_gig',
            },
        ),
        migrations.CreateModel(
            name='SellerFaq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default='', max_length=250)),
                ('answer', models.CharField(default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('gig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WpGig.gig')),
            ],
            options={
                'db_table': 'core_wpgig_sellerfaq',
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Basic', 'Basic'), ('Standard', 'Standard'), ('Premium', 'Premium'), ('Custom', 'Custom')], default='Standard', max_length=15)),
                ('description', models.TextField(default='')),
                ('price', models.CharField(default='', max_length=50)),
                ('show_price', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('gig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WpGig.gig')),
            ],
            options={
                'db_table': 'core_wpgig_package',
            },
        ),
        migrations.CreateModel(
            name='Gallary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to=CORE.WeddingPlanner.WpGig.models.upload_location)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('gig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WpGig.gig')),
            ],
            options={
                'db_table': 'core_wpgig_gallary',
            },
        ),
    ]
