# Generated by Django 4.2.1 on 2023-06-30 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('picture', models.ImageField(null=True, upload_to='')),
                ('bio', models.CharField(default='', max_length=250)),
                ('details_info', models.TextField(default='')),
                ('joining_date', models.DateField(auto_now_add=True)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('is_archived', models.BooleanField(default=False)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_wpseller_portfolio',
            },
        ),
        migrations.CreateModel(
            name='RecentWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=250)),
                ('description', models.TextField(default='')),
                ('picture', models.ImageField(null=True, upload_to='')),
                ('date', models.DateField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WpSeller.portfolio')),
            ],
            options={
                'db_table': 'core_wpseller_recentwork',
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(default='', max_length=15)),
                ('email', models.CharField(default='', max_length=100)),
                ('address', models.CharField(default='', max_length=250)),
                ('website', models.CharField(default='', max_length=50)),
                ('facebook', models.CharField(default='', max_length=100)),
                ('instagram', models.CharField(default='', max_length=100)),
                ('twitter', models.CharField(default='', max_length=100)),
                ('behance', models.CharField(default='', max_length=100)),
                ('whatsapp', models.CharField(default='', max_length=100)),
                ('telegram', models.CharField(default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('portfolio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='WpSeller.portfolio')),
            ],
            options={
                'db_table': 'core_wpseller_contactinfo',
            },
        ),
    ]
