# Generated by Django 4.2.1 on 2023-07-02 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WpSeller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'core_wpseller_tag',
            },
        ),
        migrations.CreateModel(
            name='SellerTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WpSeller.portfolio')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WpSeller.tag')),
            ],
            options={
                'db_table': 'core_wpseller_sellertag',
            },
        ),
    ]
