# Generated by Django 4.2.1 on 2023-07-15 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'matrimony_profile',
            },
        ),
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.ImageField(blank=True, null=True, upload_to='matrimony/profile/')),
                ('label', models.CharField(default='', max_length=100)),
                ('is_private', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MatrimonyProfile.profile')),
            ],
            options={
                'db_table': 'matrimony_profile_profileimage',
            },
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employment_type', models.CharField(choices=[('Government', 'Government'), ('Private', 'Private'), ('Business', 'Business'), ('Defence', 'Defence'), ('Self Employed', 'Self Employed'), ('Not Working', 'Not Working')], default='Private', max_length=15)),
                ('occupation', models.CharField(default='', max_length=20)),
                ('occupation_details', models.CharField(default='', max_length=500)),
                ('organization', models.CharField(default='', max_length=100)),
                ('annual_income', models.PositiveIntegerField(null=True)),
                ('currency', models.CharField(default='BDT', max_length=10)),
                ('is_archived', models.BooleanField(default=False)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='MatrimonyProfile.profile')),
            ],
            options={
                'db_table': 'matrimony_profile_profession',
            },
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_range', models.CharField(default='25-35', max_length=10)),
                ('height_range', models.CharField(default='155-185', max_length=15)),
                ('complexion', models.CharField(choices=[('Fair', 'Fair'), ('Very Fair', 'Very Fair'), ('Wheatish', 'Wheatish'), ('Brown', 'Brown'), ('Dark', 'Dark')], default='Fair', max_length=15)),
                ('marital_status', models.CharField(choices=[('Never Married', 'Never Married'), ('Married', 'Married'), ('Widowed', 'Widowed'), ('Awaiting Divorce', 'Awaiting Divorce'), ('Divorced', 'Divorced'), ('Anulled', 'Anulled')], default='Never Married', max_length=20)),
                ('mother_tongue', models.CharField(default='Bengali', max_length=10)),
                ('religion', models.CharField(choices=[('Muslim', 'Muslim'), ('Hindu', 'Hindu'), ('Christian', 'Christian'), ('Biddhist', 'Buddhist'), ('Other', 'Other')], default='Muslim', max_length=10)),
                ('city', models.CharField(default='Dhaka', max_length=20)),
                ('country', models.CharField(default='Bangladesh', max_length=20)),
                ('residential_status', models.CharField(choices=[('Citizen', 'Citizen'), ('Permanent Resident', 'Permanent Resident'), ('Work Permit', 'Work Permit'), ('Student Visa', 'Student Visa')], default='Citizen', max_length=20)),
                ('highest_education', models.CharField(default='', max_length=20)),
                ('employment_type', models.CharField(choices=[('Government', 'Government'), ('Private', 'Private'), ('Business', 'Business'), ('Defence', 'Defence'), ('Self Employed', 'Self Employed'), ('Not Working', 'Not Working')], default='Private', max_length=15)),
                ('annual_income', models.PositiveIntegerField(null=True)),
                ('currency', models.CharField(default='BDT', max_length=10)),
                ('family_type', models.CharField(choices=[('Joint', 'Joint'), ('Nuclear', 'Nuclear')], default='Nuclear', max_length=10)),
                ('family_status', models.CharField(choices=[('Lower Class', 'Lower Class'), ('Middle Class', 'Middle Class'), ('Upper-Middle Class', 'Upper Middle Class'), ('Upper Class', 'Upper Class')], default='Middle Class', max_length=20)),
                ('family_culture', models.CharField(choices=[('Traditional', 'Traditional'), ('Moderate', 'Moderate'), ('Liberal', 'Liberal')], default='Moderate', max_length=15)),
                ('eating_habit', models.CharField(choices=[('Vegetarian', 'Vegetarian'), ('Vegan', 'Vegan'), ('Non Vegetarian', 'Non Vegetarian')], default='Non Vegetarian', max_length=20)),
                ('drinking_habit', models.CharField(choices=[('No', 'No'), ('Yes', 'Yes'), ('Occasionally', 'Occasionally')], default='No', max_length=20)),
                ('smoking_habit', models.CharField(choices=[('No', 'No'), ('Yes', 'Yes'), ('Occasionally', 'Occasionally')], default='No', max_length=20)),
                ('description', models.CharField(default='', max_length=500)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='MatrimonyProfile.profile')),
            ],
            options={
                'db_table': 'matrimony_profile_preference',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default='Dhaka', max_length=20)),
                ('state', models.CharField(default='Dhaka', max_length=20)),
                ('country', models.CharField(default='Bangladesh', max_length=20)),
                ('category', models.CharField(default='Present', max_length=10)),
                ('is_archived', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MatrimonyProfile.profile')),
            ],
            options={
                'db_table': 'matrimony_profile_location',
            },
        ),
        migrations.CreateModel(
            name='FilterConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strict_age', models.BooleanField(default=False)),
                ('strict_height', models.BooleanField(default=False)),
                ('strict_complexion', models.BooleanField(default=False)),
                ('strict_marital_status', models.BooleanField(default=False)),
                ('strict_religion', models.BooleanField(default=False)),
                ('strict_city', models.BooleanField(default=False)),
                ('strict_employment_type', models.BooleanField(default=False)),
                ('strict_family_type', models.BooleanField(default=False)),
                ('strict_family_status', models.BooleanField(default=False)),
                ('strict_family_culture', models.BooleanField(default=False)),
                ('strict_eating_habit', models.BooleanField(default=False)),
                ('strict_drinking_habit', models.BooleanField(default=False)),
                ('strict_smoking_habit', models.BooleanField(default=False)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='MatrimonyProfile.profile')),
            ],
            options={
                'db_table': 'matrimony_profile_filterconfiguration',
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(default='', max_length=100)),
                ('father_occupation', models.CharField(default='', max_length=50)),
                ('mother_name', models.CharField(default='', max_length=100)),
                ('mother_occupation', models.CharField(default='', max_length=50)),
                ('no_of_brothers', models.PositiveIntegerField(default=0)),
                ('no_of_brothers_married', models.PositiveIntegerField(default=0)),
                ('no_of_sisters', models.PositiveIntegerField(default=0)),
                ('no_of_sisters_married', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(choices=[('Joint', 'Joint'), ('Nuclear', 'Nuclear')], default='Nuclear', max_length=10)),
                ('status', models.CharField(choices=[('Lower Class', 'Lower Class'), ('Middle Class', 'Middle Class'), ('Upper-Middle Class', 'Upper Middle Class'), ('Upper Class', 'Upper Class')], default='Middle Class', max_length=20)),
                ('culture', models.CharField(choices=[('Traditional', 'Traditional'), ('Moderate', 'Moderate'), ('Liberal', 'Liberal')], default='Moderate', max_length=15)),
                ('location', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=250)),
                ('is_archived', models.BooleanField(default=False)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='MatrimonyProfile.profile')),
            ],
            options={
                'db_table': 'matrimony_profile_family',
            },
        ),
        migrations.CreateModel(
            name='ExtraInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_type', models.CharField(choices=[('Slim', 'Slim'), ('Athletic', 'Athletic'), ('Average', 'Average'), ('Heavy', 'Heavy')], default='Average', max_length=20)),
                ('eating_habit', models.CharField(choices=[('Vegetarian', 'Vegetarian'), ('Vegan', 'Vegan'), ('Non Vegetarian', 'Non Vegetarian')], default='Non Vegetarian', max_length=20)),
                ('drinking_habit', models.CharField(choices=[('No', 'No'), ('Yes', 'Yes'), ('Occasionally', 'Occasionally')], default='No', max_length=20)),
                ('smoking_habit', models.CharField(choices=[('No', 'No'), ('Yes', 'Yes'), ('Occasionally', 'Occasionally')], default='No', max_length=20)),
                ('is_archived', models.BooleanField(default=False)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='MatrimonyProfile.profile')),
            ],
            options={
                'db_table': 'matrimony_profile_extrainformation',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=20)),
                ('institution', models.CharField(default='', max_length=100)),
                ('passing_year', models.PositiveIntegerField(null=True)),
                ('details', models.CharField(default='', max_length=250)),
                ('is_archived', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MatrimonyProfile.profile')),
            ],
            options={
                'db_table': 'matrimony_profile_education',
            },
        ),
        migrations.CreateModel(
            name='Citizenship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='Bangladesh', max_length=20)),
                ('status', models.CharField(choices=[('Citizen', 'Citizen'), ('Permanent Resident', 'Permanent Resident'), ('Work Permit', 'Work Permit'), ('Student Visa', 'Student Visa')], default='Citizen', max_length=20)),
                ('is_archived', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MatrimonyProfile.profile')),
            ],
            options={
                'db_table': 'matrimony_profile_citizenship',
            },
        ),
        migrations.CreateModel(
            name='BasicInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(default='', max_length=50)),
                ('date_of_birth', models.DateField(null=True)),
                ('place_of_birth', models.CharField(default='', max_length=20)),
                ('height', models.CharField(default='', max_length=20)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('weight_lbs', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('complexion', models.CharField(choices=[('Fair', 'Fair'), ('Very Fair', 'Very Fair'), ('Wheatish', 'Wheatish'), ('Brown', 'Brown'), ('Dark', 'Dark')], default='Fair', max_length=15)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='matrimony/profile/')),
                ('physical_status', models.CharField(default='Normal', max_length=10)),
                ('marital_status', models.CharField(choices=[('Never Married', 'Never Married'), ('Married', 'Married'), ('Widowed', 'Widowed'), ('Awaiting Divorce', 'Awaiting Divorce'), ('Divorced', 'Divorced'), ('Anulled', 'Anulled')], default='Never Married', max_length=20)),
                ('children_count', models.PositiveIntegerField(default=0)),
                ('mother_tongue', models.CharField(default='Bengali', max_length=10)),
                ('religion', models.CharField(choices=[('Muslim', 'Muslim'), ('Hindu', 'Hindu'), ('Christian', 'Christian'), ('Biddhist', 'Buddhist'), ('Other', 'Other')], default='Muslim', max_length=10)),
                ('blood_group', models.CharField(default='Not Know', max_length=10)),
                ('is_archived', models.BooleanField(default=False)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='MatrimonyProfile.profile')),
            ],
            options={
                'db_table': 'matrimony_profile_basicinformation',
            },
        ),
    ]
